server:
  port: 8013
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tb_product?characterEndcoding=utf-8&useSSL=false
    username: root
    password: likeTuhua1314
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  instance:
    prefer-ip-address: false

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka