server:
  port: 8888
spring:
  profiles:
    active: k8s
  application:
    name: @artifactId@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-client
          uri: lb://product-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/product/**
        - id: user-service
          uri: lb://user-service
          filters:
            - StripPrefix=1
          predicates:
            - Path=/user/**
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true
    fetch-registry: true