server:
  port: 8018
spring:
  application:
    name: product-client
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8888/eureka

feign:
  hystrix:
    enabled: true #开启Hystrix 断路器
